#!/bin/bash

./bin/server -t cubic -p 5000 >> /dev/null &
./bin/server -t cubic -p 5001 >> /dev/null &
./bin/server -t cubic -p 5002 >> /dev/null &
./bin/server -t cubic -p 5003 >> /dev/null &
./bin/server -t cubic -p 5004 >> /dev/null &
./bin/server -t cubic -p 5005 >> /dev/null &
./bin/server -t cubic -p 5006 >> /dev/null &
./bin/server -t cubic -p 5007 >> /dev/null &
./bin/server -t cubic -p 5008 >> /dev/null &
./bin/server -t cubic -p 5009 >> /dev/null &
./bin/server -t cubic -p 5010 >> /dev/null &
./bin/server -t cubic -p 5011 >> /dev/null &
./bin/server -t cubic -p 5012 >> /dev/null &
./bin/server -t cubic -p 5013 >> /dev/null &
./bin/server -t cubic -p 5014 >> /dev/null &
./bin/server -t cubic -p 5015 >> /dev/null &
./bin/server -t cubic -p 5016 >> /dev/null &
./bin/server -t cubic -p 5017 >> /dev/null &
./bin/server -t cubic -p 5018 >> /dev/null &
./bin/server -t cubic -p 5019 >> /dev/null &
./bin/server -t cubic -p 5020 >> /dev/null &
./bin/server -t cubic -p 5021 >> /dev/null &
./bin/server -t cubic -p 5022 >> /dev/null &
./bin/server -t cubic -p 5023 >> /dev/null &
./bin/server -t cubic -p 5024 >> /dev/null &
./bin/server -t cubic -p 5025 >> /dev/null &
./bin/server -t cubic -p 5026 >> /dev/null &
./bin/server -t cubic -p 5027 >> /dev/null &
./bin/server -t cubic -p 5028 >> /dev/null &
./bin/server -t cubic -p 5029 >> /dev/null &
./bin/server -t cubic -p 5030 >> /dev/null &
./bin/server -t cubic -p 5031 >> /dev/null &
./bin/server -t cubic -p 5032 >> /dev/null &
./bin/server -t cubic -p 5033 >> /dev/null &
./bin/server -t cubic -p 5034 >> /dev/null &
./bin/server -t cubic -p 5035 >> /dev/null &
./bin/server -t cubic -p 5036 >> /dev/null &
./bin/server -t cubic -p 5037 >> /dev/null &
./bin/server -t cubic -p 5038 >> /dev/null &
./bin/server -t cubic -p 5039 >> /dev/null &
./bin/server -t cubic -p 5040 >> /dev/null &
./bin/server -t cubic -p 5041 >> /dev/null &
./bin/server -t cubic -p 5042 >> /dev/null &
./bin/server -t cubic -p 5043 >> /dev/null &
./bin/server -t cubic -p 5044 >> /dev/null &
./bin/server -t cubic -p 5045 >> /dev/null &
./bin/server -t cubic -p 5046 >> /dev/null &
./bin/server -t cubic -p 5047 >> /dev/null &
./bin/server -t cubic -p 5048 >> /dev/null &
./bin/server -t cubic -p 5049 >> /dev/null &
./bin/server -t cubic -p 5050 >> /dev/null &
./bin/server -t cubic -p 5051 >> /dev/null &
./bin/server -t cubic -p 5052 >> /dev/null &
./bin/server -t cubic -p 5053 >> /dev/null &
./bin/server -t cubic -p 5054 >> /dev/null &
./bin/server -t cubic -p 5055 >> /dev/null &
./bin/server -t cubic -p 5056 >> /dev/null &
./bin/server -t cubic -p 5057 >> /dev/null &
./bin/server -t cubic -p 5058 >> /dev/null &
./bin/server -t cubic -p 5059 >> /dev/null &
./bin/server -t cubic -p 5060 >> /dev/null &
./bin/server -t cubic -p 5061 >> /dev/null &
./bin/server -t cubic -p 5062 >> /dev/null &
./bin/server -t cubic -p 5063 >> /dev/null &
./bin/server -t cubic -p 5064 >> /dev/null &
./bin/server -t cubic -p 5065 >> /dev/null &
./bin/server -t cubic -p 5066 >> /dev/null &
./bin/server -t cubic -p 5067 >> /dev/null &
./bin/server -t cubic -p 5068 >> /dev/null &
./bin/server -t cubic -p 5069 >> /dev/null &
./bin/server -t cubic -p 5070 >> /dev/null &
./bin/server -t cubic -p 5071 >> /dev/null &
./bin/server -t cubic -p 5072 >> /dev/null &
./bin/server -t cubic -p 5073 >> /dev/null &
./bin/server -t cubic -p 5074 >> /dev/null &
./bin/server -t cubic -p 5075 >> /dev/null &
./bin/server -t cubic -p 5076 >> /dev/null &
./bin/server -t cubic -p 5077 >> /dev/null &
./bin/server -t cubic -p 5078 >> /dev/null &
./bin/server -t cubic -p 5079 >> /dev/null &
./bin/server -t cubic -p 5080 >> /dev/null &
./bin/server -t cubic -p 5081 >> /dev/null &
./bin/server -t cubic -p 5082 >> /dev/null &
./bin/server -t cubic -p 5083 >> /dev/null &
./bin/server -t cubic -p 5084 >> /dev/null &
./bin/server -t cubic -p 5085 >> /dev/null &
./bin/server -t cubic -p 5086 >> /dev/null &
./bin/server -t cubic -p 5087 >> /dev/null &
./bin/server -t cubic -p 5088 >> /dev/null &
./bin/server -t cubic -p 5089 >> /dev/null &
./bin/server -t cubic -p 5090 >> /dev/null &
./bin/server -t cubic -p 5091 >> /dev/null &
./bin/server -t cubic -p 5092 >> /dev/null &
./bin/server -t cubic -p 5093 >> /dev/null &
./bin/server -t cubic -p 5094 >> /dev/null &
./bin/server -t cubic -p 5095 >> /dev/null &
./bin/server -t cubic -p 5096 >> /dev/null &
./bin/server -t cubic -p 5097 >> /dev/null &
./bin/server -t cubic -p 5098 >> /dev/null &
./bin/server -t cubic -p 5099 >> /dev/null &
./bin/server -t cubic -p 5100 >> /dev/null &
./bin/server -t cubic -p 5101 >> /dev/null &
./bin/server -t cubic -p 5102 >> /dev/null &
./bin/server -t cubic -p 5103 >> /dev/null &
./bin/server -t cubic -p 5104 >> /dev/null &
./bin/server -t cubic -p 5105 >> /dev/null &
./bin/server -t cubic -p 5106 >> /dev/null &
./bin/server -t cubic -p 5107 >> /dev/null &
./bin/server -t cubic -p 5108 >> /dev/null &
./bin/server -t cubic -p 5109 >> /dev/null &
./bin/server -t cubic -p 5110 >> /dev/null &
./bin/server -t cubic -p 5111 >> /dev/null &
./bin/server -t cubic -p 5112 >> /dev/null &
./bin/server -t cubic -p 5113 >> /dev/null &
./bin/server -t cubic -p 5114 >> /dev/null &
./bin/server -t cubic -p 5115 >> /dev/null &
./bin/server -t cubic -p 5116 >> /dev/null &
./bin/server -t cubic -p 5117 >> /dev/null &
./bin/server -t cubic -p 5118 >> /dev/null &
./bin/server -t cubic -p 5119 >> /dev/null &
./bin/server -t cubic -p 5120 >> /dev/null &
./bin/server -t cubic -p 5121 >> /dev/null &
./bin/server -t cubic -p 5122 >> /dev/null &
./bin/server -t cubic -p 5123 >> /dev/null &
./bin/server -t cubic -p 5124 >> /dev/null &
./bin/server -t cubic -p 5125 >> /dev/null &
./bin/server -t cubic -p 5126 >> /dev/null &
./bin/server -t cubic -p 5127 >> /dev/null &
./bin/server -t cubic -p 5128 >> /dev/null &
./bin/server -t cubic -p 5129 >> /dev/null &
./bin/server -t cubic -p 5130 >> /dev/null &
./bin/server -t cubic -p 5131 >> /dev/null &
./bin/server -t cubic -p 5132 >> /dev/null &
./bin/server -t cubic -p 5133 >> /dev/null &
./bin/server -t cubic -p 5134 >> /dev/null &
./bin/server -t cubic -p 5135 >> /dev/null &
./bin/server -t cubic -p 5136 >> /dev/null &
./bin/server -t cubic -p 5137 >> /dev/null &
./bin/server -t cubic -p 5138 >> /dev/null &
./bin/server -t cubic -p 5139 >> /dev/null &
./bin/server -t cubic -p 5140 >> /dev/null &
./bin/server -t cubic -p 5141 >> /dev/null &
./bin/server -t cubic -p 5142 >> /dev/null &
./bin/server -t cubic -p 5143 >> /dev/null &
./bin/server -t cubic -p 5144 >> /dev/null &
./bin/server -t cubic -p 5145 >> /dev/null &
./bin/server -t cubic -p 5146 >> /dev/null &
./bin/server -t cubic -p 5147 >> /dev/null &
./bin/server -t cubic -p 5148 >> /dev/null &
./bin/server -t cubic -p 5149 >> /dev/null &
./bin/server -t cubic -p 5150 >> /dev/null &
./bin/server -t cubic -p 5151 >> /dev/null &
./bin/server -t cubic -p 5152 >> /dev/null &
./bin/server -t cubic -p 5153 >> /dev/null &
./bin/server -t cubic -p 5154 >> /dev/null &
./bin/server -t cubic -p 5155 >> /dev/null &
./bin/server -t cubic -p 5156 >> /dev/null &
./bin/server -t cubic -p 5157 >> /dev/null &
./bin/server -t cubic -p 5158 >> /dev/null &
./bin/server -t cubic -p 5159 >> /dev/null &
./bin/server -t cubic -p 5160 >> /dev/null &
./bin/server -t cubic -p 5161 >> /dev/null &
./bin/server -t cubic -p 5162 >> /dev/null &
./bin/server -t cubic -p 5163 >> /dev/null &
./bin/server -t cubic -p 5164 >> /dev/null &
./bin/server -t cubic -p 5165 >> /dev/null &
./bin/server -t cubic -p 5166 >> /dev/null &
./bin/server -t cubic -p 5167 >> /dev/null &
./bin/server -t cubic -p 5168 >> /dev/null &
./bin/server -t cubic -p 5169 >> /dev/null &
./bin/server -t cubic -p 5170 >> /dev/null &
./bin/server -t cubic -p 5171 >> /dev/null &
./bin/server -t cubic -p 5172 >> /dev/null &
./bin/server -t cubic -p 5173 >> /dev/null &
./bin/server -t cubic -p 5174 >> /dev/null &
./bin/server -t cubic -p 5175 >> /dev/null &
./bin/server -t cubic -p 5176 >> /dev/null &
./bin/server -t cubic -p 5177 >> /dev/null &
./bin/server -t cubic -p 5178 >> /dev/null &
./bin/server -t cubic -p 5179 >> /dev/null &
./bin/server -t cubic -p 5180 >> /dev/null &
./bin/server -t cubic -p 5181 >> /dev/null &
./bin/server -t cubic -p 5182 >> /dev/null &
./bin/server -t cubic -p 5183 >> /dev/null &
./bin/server -t cubic -p 5184 >> /dev/null &
./bin/server -t cubic -p 5185 >> /dev/null &
./bin/server -t cubic -p 5186 >> /dev/null &
./bin/server -t cubic -p 5187 >> /dev/null &
./bin/server -t cubic -p 5188 >> /dev/null &
./bin/server -t cubic -p 5189 >> /dev/null &
./bin/server -t cubic -p 5190 >> /dev/null &
./bin/server -t cubic -p 5191 >> /dev/null &
./bin/server -t cubic -p 5192 >> /dev/null &
./bin/server -t cubic -p 5193 >> /dev/null &
./bin/server -t cubic -p 5194 >> /dev/null &
./bin/server -t cubic -p 5195 >> /dev/null &
./bin/server -t cubic -p 5196 >> /dev/null &
./bin/server -t cubic -p 5197 >> /dev/null &
./bin/server -t cubic -p 5198 >> /dev/null &
./bin/server -t cubic -p 5199 >> /dev/null &
./bin/server -t ccp -p 5200 >> /dev/null &
